# Generated by Django 6.0.2 on 2026-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mood_mood_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='date',
        ),
        migrations.AddField(
            model_name='mood',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
